global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "frontend"
    static_configs:
      - targets: ["frontend:3000"]
        labels:
          group: "frontend"

  - job_name: "redis"
    static_configs:
      - targets: ["redis:6379"]
        labels:
          group: "redis"
