apiVersion: apps/v1
kind: Deployment
metadata:
  name: infnet-frontend-deployment
  labels:
    app: infnet-frontend
spec:
  replicas: 4
  selector:
    matchLabels:
      app: infnet-frontend
  template:
    metadata:
      labels:
        app: infnet-frontend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
    spec:
      containers:
        - name: infnet-frontend
          image: meirajh/infnet-arq-ci-cd
          ports:
            - containerPort: 3000
          env:
            - name: REDIS_HOST
              value: "redis-service"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 1
            failureThreshold: 1
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: infnet-frontend-service
spec:
  type: NodePort
  selector:
    app: infnet-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 32000
