version: "3.8"

services:
  nextjs:
    image: meirajh/infnet-arq-ci-cd:latest
    deploy:
      replicas: 3 # Runs 3 instances of your app
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
      restart_policy:
        condition: on-failure
    ports:
      - "3000:3000" # Maps host:3000 → container:3000
    networks:
      - nextjs-net

networks:
  nextjs-net:
    driver: overlay # Swarm-specific network for multi-host communication
