name: Build and Push Docker Image with Semantic Tag

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Extraction package.json
        id: version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version_tag=$VERSION" >> $GITHUB_OUTPUT

      - name: Dockerhub Login
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Docker image build
        run: |
          docker build -t meirajh/infnet-arq-ci-cd:${{ steps.version.outputs.version_tag }} .
          docker tag meirajh/infnet-arq-ci-cd:${{ steps.version.outputs.version_tag }} meirajh/infnet-arq-ci-cd:latest

      - name: Image push with :latest tag
        run: |
          docker push meirajh/infnet-arq-ci-cd:${{ steps.version.outputs.version_tag }}
          docker push meirajh/infnet-arq-ci-cd:latest
