name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: "./frontend"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "yarn"
          cache-dependency-path: "./frontend/yarn.lock"

      - name: Extract version
        id: version
        working-directory: ./frontend
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version_tag=$VERSION" >> $GITHUB_OUTPUT
          echo "Using version: $VERSION"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        working-directory: ./frontend
        run: |
          docker build \
            -t meirajh/infnet-arq-ci-cd:${{ steps.version.outputs.version_tag }} \
            -t meirajh/infnet-arq-ci-cd:latest \
            .

      - name: Push Docker images
        run: |
          docker push meirajh/infnet-arq-ci-cd:${{ steps.version.outputs.version_tag }}
          docker push meirajh/infnet-arq-ci-cd:latest
